function cartesianas(X1, Y1, X2, Y2, X3, YMatrix1)
%CREATEFIGURE(X1, Y1, X2, Y2, X3, YMatrix1)
%  X1:  vector of x data
%  Y1:  vector of y data
%  X2:  vector of x data
%  Y2:  vector of y data
%  X3:  vector of x data
%  YMATRIX1:  matrix of y data

%  Auto-generated by MATLAB on 23-Jan-2019 14:06:11

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');

% Create plot
plot(X1,Y1,'DisplayName','Trayectoria referencia','LineWidth',2,...
    'Color',[0 0 1]);

% Create plot
plot(X2,Y2,'DisplayName','Trayectoria real','LineWidth',2,...
    'Color',[0.800000011920929 0 0]);

% Create multiple lines using matrix input to plot
plot1 = plot(X3,YMatrix1,'MarkerSize',18,'LineWidth',3,'LineStyle','none',...
    'Color',[0 0 0]);
set(plot1(1),'DisplayName','Base del brazo','Marker','o');
set(plot1(2),'DisplayName','Posición descanso','Marker','v');

% Create ylabel
ylabel('Y (m)');

% Create xlabel
xlabel('X (m)');

% Create title
title('Trayectoria de extremo del robot referencia frente a real');

box(axes1,'on');
grid(axes1,'on');
% Set the remaining axes properties
set(axes1,'FontSize',19);
% Create legend
legend(axes1,'show');

