function Grafica21(X1, YMatrix1, YMatrix2)
%CREATEFIGURE(X1, YMatrix1, YMatrix2)
%  X1:  vector of x data
%  YMATRIX1:  matrix of y data
%  YMATRIX2:  matrix of y data

%  Auto-generated by MATLAB on 23-Jan-2019 13:56:29

% Create figure
figure1 = figure;

% Create subplot
subplot1 = subplot(2,1,1,'Parent',figure1);
hold(subplot1,'on');

% Create multiple lines using matrix input to plot
plot1 = plot(X1,YMatrix1,'Parent',subplot1,'LineWidth',2);
set(plot1(1),'DisplayName','Error posición q1',...
    'Color',[0.20392157137394 0.301960796117783 0.494117647409439]);
set(plot1(2),'DisplayName','Error posición q2',...
    'Color',[0.756862759590149 0.866666674613953 0.776470601558685]);

% Create ylabel
ylabel('Posición (rad)');

% Create xlabel
xlabel('Tiempo (s)');

% Create title
title('Errores de posición articular');

box(subplot1,'on');
grid(subplot1,'on');
% Set the remaining axes properties
set(subplot1,'FontSize',19);
% Create legend
legend1 = legend(subplot1,'show');
set(legend1,'FontSize',20);

% Create subplot
subplot2 = subplot(2,1,2,'Parent',figure1);
hold(subplot2,'on');

% Create multiple lines using matrix input to plot
plot2 = plot(X1,YMatrix2,'Parent',subplot2,'LineWidth',2);
set(plot2(1),'DisplayName','Error velocidad q1',...
    'Color',[0.20392157137394 0.301960796117783 0.494117647409439]);
set(plot2(2),'DisplayName','Error velocidad q2',...
    'MarkerFaceColor',[0.756862759590149 0.866666674613953 0.776470601558685],...
    'Color',[0.756862759590149 0.866666674613953 0.776470601558685]);

% Create ylabel
ylabel('Velocidad (rad/s)');

% Create xlabel
xlabel('Tiempo (s)');

% Create title
title('Errores de velocidad articular');

box(subplot2,'on');
grid(subplot2,'on');
% Set the remaining axes properties
set(subplot2,'FontSize',18);
% Create legend
legend2 = legend(subplot2,'show');
set(legend2,'FontSize',20);

