function Grafica11(X1, YMatrix1)
%CREATEFIGURE(X1, YMatrix1)
%  X1:  vector of x data
%  YMATRIX1:  matrix of y data

%  Auto-generated by MATLAB on 23-Jan-2019 12:42:04

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');

% Create multiple lines using matrix input to plot
plot1 = plot(X1,YMatrix1,'LineWidth',2);
set(plot1(1),'DisplayName','Posición deseada','Color',[0 0 1]);
set(plot1(2),'DisplayName','Posición real','Color',[1 0 0]);

% Create ylabel
ylabel('Posición articular (rad)','FontSize',20);

% Create xlabel
xlabel('Tiempo (s)','FontSize',20);

% Create title
title('Posición articular 1 de referencia frente a real','FontSize',23);

box(axes1,'on');
grid(axes1,'on');
% Set the remaining axes properties
set(axes1,'FontSize',18);
% Create legend
legend1 = legend(axes1,'show');
set(legend1,'FontSize',20);

