function createfigure(X1, YMatrix1, X2, YMatrix2)
%CREATEFIGURE(X1, YMatrix1, X2, YMatrix2)
%  X1:  vector of x data
%  YMATRIX1:  matrix of y data
%  X2:  vector of x data
%  YMATRIX2:  matrix of y data

%  Auto-generated by MATLAB on 28-Jan-2019 01:22:51

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');

% Create multiple lines using matrix input to plot
plot1 = plot(X1,YMatrix1,'LineWidth',2);
set(plot1(1),'DisplayName','Posición deseada q1');
set(plot1(2),'DisplayName','Posición deseada q2');

% Create multiple lines using matrix input to plot
plot2 = plot(X2,YMatrix2,'LineWidth',2);
set(plot2(1),'DisplayName','Posición real q1');
set(plot2(2),'DisplayName','Posición real q2');

% Create ylabel
ylabel('Posición articular (rad)');

% Create xlabel
xlabel('Tiempo (s)');

% Create title
title('Posiciones articulares de referencia frente a real');

box(axes1,'on');
grid(axes1,'on');
% Set the remaining axes properties
set(axes1,'FontSize',19);
% Create legend
legend1 = legend(axes1,'show');
set(legend1,...
    'Position',[0.153176653342321 0.75551087386456 0.136979163375994 0.135906036401488]);

