function createfigure(X1, YMatrix1, X2, YMatrix2)
%CREATEFIGURE(X1, YMatrix1, X2, YMatrix2)
%  X1:  vector of x data
%  YMATRIX1:  matrix of y data
%  X2:  vector of x data
%  YMATRIX2:  matrix of y data

%  Auto-generated by MATLAB on 28-Jan-2019 01:38:59

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');

% Create multiple lines using matrix input to plot
plot1 = plot(X1,YMatrix1,'LineWidth',2);
set(plot1(1),'DisplayName',' Velocidad deseada q1');
set(plot1(2),'DisplayName','Velocidad deseada q2');

% Create multiple lines using matrix input to plot
plot2 = plot(X2,YMatrix2,'LineWidth',2);
set(plot2(1),'DisplayName','Velocidad real q1');
set(plot2(2),'DisplayName','Velocidad real q2');

% Create ylabel
ylabel('Velocidad (rad/s)');

% Create xlabel
xlabel('Tiempo (s)');

% Create title
title('Velocidades articulares de referencia frente a real');

box(axes1,'on');
grid(axes1,'on');
% Set the remaining axes properties
set(axes1,'FontSize',19);
% Create legend
legend1 = legend(axes1,'show');
set(legend1,...
    'Position',[0.166718320164208 0.682732602487982 0.147395829732219 0.206632647181855]);

